#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
Name     : bash.static
Version  : 4.4.18
Release  : 51
URL      : https://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz
Source0  : https://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz
Source1  : https://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz.sig
Summary  : Bash headers for bash loadable builtins
Group    : Development/Tools
License  : GPL-3.0
Requires: bash.static-bin = %{version}-%{release}
Requires: bash.static-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : glibc-staticdev
BuildRequires : ncurses-dev
Patch1: nodlopen.patch
Patch2: stateless.patch
Patch3: 0001-Support-stateless-inputrc-configuration.patch
Patch4: cve-2017-5932.nopatch

%description
Introduction
============
This is GNU Bash, version 4.4.  Bash is the GNU Project's Bourne
Again SHell, a complete implementation of the POSIX shell spec,
but also with interactive command line editing, job control on
architectures that support it, csh-like features such as history
substitution and brace expansion, and a slew of other features.
For more information on the features of Bash that are new to this
type of shell, see the file `doc/bashref.texi'.  There is also a
large Unix-style man page.  The man page is the definitive description
of the shell's features.

%package bin
Summary: bin components for the bash.static package.
Group: Binaries
Requires: bash.static-license = %{version}-%{release}

%description bin
bin components for the bash.static package.


%package license
Summary: license components for the bash.static package.
Group: Default

%description license
license components for the bash.static package.


%prep
%setup -q -n bash-4.4.18
cd %{_builddir}/bash-4.4.18
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579889930
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-bash-malloc=no --enable-static-link --disable-nls --without-rpath
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1579889930
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bash.static
cp %{_builddir}/bash-4.4.18/COPYING %{buildroot}/usr/share/package-licenses/bash.static/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/bash-4.4.18/lib/readline/COPYING %{buildroot}/usr/share/package-licenses/bash.static/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/bash-4.4.18/tests/COPYRIGHT %{buildroot}/usr/share/package-licenses/bash.static/771f6b3c33dd1c00e5d2f319cb801d0611ddd699
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/share/doc/bash/CHANGES
rm -f %{buildroot}/usr/share/doc/bash/COMPAT
rm -f %{buildroot}/usr/share/doc/bash/FAQ
rm -f %{buildroot}/usr/share/doc/bash/INTRO
rm -f %{buildroot}/usr/share/doc/bash/NEWS
rm -f %{buildroot}/usr/share/doc/bash/POSIX
rm -f %{buildroot}/usr/share/doc/bash/RBASH
rm -f %{buildroot}/usr/share/doc/bash/README
rm -f %{buildroot}/usr/share/doc/bash/bash.html
rm -f %{buildroot}/usr/share/doc/bash/bashref.html
rm -f %{buildroot}/usr/share/info/bash.info
rm -f %{buildroot}/usr/share/man/man1/bash.1
rm -f %{buildroot}/usr/share/man/man1/bashbug.1
rm -f %{buildroot}/usr/bin/bashbug
## install_append content
mv %{buildroot}/usr/bin/bash %{buildroot}/usr/bin/bash.static
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bash.static

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bash.static/771f6b3c33dd1c00e5d2f319cb801d0611ddd699
/usr/share/package-licenses/bash.static/8624bcdae55baeef00cd11d5dfcfa60f68710a02
