#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
Name     : bash.static
Version  : 4.4.18
Release  : 46
URL      : http://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz
Source0  : http://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz
Source99 : http://mirrors.kernel.org/gnu/bash/bash-4.4.18.tar.gz.sig
Summary  : Bash headers for bash loadable builtins
Group    : Development/Tools
License  : GPL-3.0
Requires: bash.static-bin
Requires: bash.static-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : glibc-staticdev
BuildRequires : ncurses-dev
Patch1: nodlopen.patch
Patch2: stateless.patch
Patch3: 0001-Support-stateless-inputrc-configuration.patch
Patch4: cve-2017-5932.nopatch

%description
Introduction
============
This is GNU Bash, version 4.4.  Bash is the GNU Project's Bourne
Again SHell, a complete implementation of the POSIX shell spec,
but also with interactive command line editing, job control on
architectures that support it, csh-like features such as history
substitution and brace expansion, and a slew of other features.
For more information on the features of Bash that are new to this
type of shell, see the file `doc/bashref.texi'.  There is also a
large Unix-style man page.  The man page is the definitive description
of the shell's features.

%package bin
Summary: bin components for the bash.static package.
Group: Binaries

%description bin
bin components for the bash.static package.


%package doc
Summary: doc components for the bash.static package.
Group: Documentation

%description doc
doc components for the bash.static package.


%prep
%setup -q -n bash-4.4.18
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525106564
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
%configure --disable-static --with-bash-malloc=no --enable-static-link --disable-nls --without-rpath
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1525106564
rm -rf %{buildroot}
%make_install
## make_install_append content
mv %{buildroot}/usr/bin/bash %{buildroot}/usr/bin/bash.static
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/bashbug
/usr/bin/bash.static

%files doc
%defattr(-,root,root,-)
%exclude /usr/share/doc/bash/CHANGES
%exclude /usr/share/doc/bash/COMPAT
%exclude /usr/share/doc/bash/FAQ
%exclude /usr/share/doc/bash/INTRO
%exclude /usr/share/doc/bash/NEWS
%exclude /usr/share/doc/bash/POSIX
%exclude /usr/share/doc/bash/RBASH
%exclude /usr/share/doc/bash/README
%exclude /usr/share/doc/bash/bash.html
%exclude /usr/share/doc/bash/bashref.html
%exclude /usr/share/info/bash.info
%exclude /usr/share/man/man1/bash.1
%exclude /usr/share/man/man1/bashbug.1
